---
- hosts: "{{node}}"
  vars:
    src: /workspace/myself/knight/dist/
    dest: /var/www/knight/public
    app_home: /usr/local/webapp/knight
  remote_user: root
  tasks:
    - name: ping
      ping:
      tags:
        - ping
    - name: sync code
      tags:
        - sync
      synchronize:
        src: "{{ src }}"
        dest: "{{ dest }}"
        delete: yes
        dest_port: 22
        rsync_opts:
          - "--exclude=.git"
          - "--exclude=node_modules"
          - "--exclude=vendor"
    - name: "build"
      shell: "cd {{ app_home }} && docker build ."
      tags:
        - build
    - name: "ci"
      shell: "cd {{app_home }} && "
